### ISSUE TITLE
Don't know how to create ISeq from: java.util.HashMap$Entry

### ISSUE THREAD

**Issue by nipra** [zcaudate-me/sigmund#1]
I'm getting following error for (sig/ps-env) and (sig/jvm-runtime)

Don't know how to create ISeq from: java.util.HashMap$Entry
  [Thrown class java.lang.IllegalArgumentException]

**Comment by hoebat** [comment]
onto it... thank for the pick up

**Comment by hoebat** [comment]
okay... it is done. I have pushed the bugfixed version to clojars. just delete the ~/.m2/repository/sigmund directory and try again.

**Comment by nipra** [comment]
Works now. Thanks.
