### ISSUE TITLE
Updating to support jre 7

### ISSUE THREAD

**Issue by hoebat** [zcaudate-me/sigmund#2]
Hi Duane. 

What you may have to do is to get sigar for jre 7 and then add it into your depencies. I haven't looked at the library for a while so thanks for the heads up. I'll take a look at it tonight but if you have some time to look at it, that'll be great.

On Sunday, October 27, 2013, Duane Bester wrote:
Hey there, I cloned your sigmund project and got the lein reps to work, but when I run the tests I get two errors. I was hoping you could point me in the right direction. The first error is a java version mismatch. I’m on a mac running java 7u40. I included my leon and java versions in the below output. 

Duanes-MacBook-Pro:sigmund duanebester$ lein test
0 [main] DEBUG Sigar  - minor version mismatch: (6!=7) java=1.6.4.129, native=1.7.0.0
org.hyperic.sigar.SigarException: minor version mismatch: (6!=7) java=1.6.4.129, native=1.7.0.0
    at org.hyperic.sigar.Sigar.checkVersion(Sigar.java:145)
    at org.hyperic.sigar.Sigar.<clinit>(Sigar.java:104)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:190)
    at sigmund.core$eval328$loading__4910__auto____329.invoke(core.clj:1)
    at sigmund.core$eval328.invoke(core.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6619)
    at clojure.lang.Compiler.eval(Compiler.java:6608)
    at clojure.lang.Compiler.load(Compiler.java:7064)
    at clojure.lang.RT.loadResourceScript(RT.java:370)
    at clojure.lang.RT.loadResourceScript(RT.java:361)
    at clojure.lang.RT.load(RT.java:440)

**Comment by hoebat** [comment]
I've compiled binaries for jre 7 on my mac and push a temporary solution onto github.... In doing so, I realised that my tests are not current…. especially test_sigar.clj  The examples on the readme are actually the most current. So use those… or just look at sigmund/core.clj

If you are on a mac, you should be able to use the most recent github push. However, if you are on another os you have to compile the most recent version of sigar. I built it using the following commands following: https://support.hyperic.com/display/SIGAR/Home;jsessionid=03FF332DA53E1A70A0B14320491EF081

> git clone git://github.com/hyperic/sigar.git sigar
> cd sigar/bindings/java
> ant

This outputs files:
- libsigar-universal-macosx.dylib (or whatever your os is)
- sigar.jar (which should be jre 7 compatible)

You then have to have the sugar.jar as well as the dynamic lib in your classpath. The dynamic lib has to be packaged inside a .jar file. Follow the instructions https://github.com/zcaudate/sigar-native-deps to package it

Hope it helps.

**Comment by tigasiap** [comment]
terimakasih atas semua http://goo.gl/72ocGX info dan beritanya, sangat menarik http://goo.gl/agUBtA dan bermanfaat. ditunggi juga postingan http://vigpowercapsulegreenworld.web.id/ yang berikutnya
